Style/HashSyntax: style ruby19 and enforced shorthand syntax
twitter/twitter-cldr-rb pull request #267
Opened 2023-08-18 08:30 UTC by noraj

I saw the following TODO to I decided to make it happens

```ruby
# TODO: convert this and all other hashes to 1.9 syntax
```

Follows rubocop [Style/HashSyntax](https://docs.rubocop.org/rubocop/cops_style.html#stylehashsyntax) default:

- EnforcedStyle: ruby19
- EnforcedShorthandSyntax: always

2023-08-18 08:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/twitter/twitter-cldr-rb?pullRequest=267) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/twitter/twitter-cldr-rb?pullRequest=267) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/twitter/twitter-cldr-rb?pullRequest=267) it.</sub>

2023-08-18 23:07 UTC, camertron requested changes
Wow, thanks for working on this! Most of your changes look good, however the lib supports a number of older Ruby versions that don't support the shorthand hash syntax introduced in Ruby 3.1, eg: `a = "b"; { a: }`. These will need to use non-shorthand syntax.

Also, please sign the CLA 😄

2023-08-21 10:11 UTC, noraj commented
Now there is the ruby 1.9 syntax without 3.1 shorthand syntax. I suggest doing a squash merge due to the dirty revert.

2023-08-22 17:50 UTC, camertron approved these changes

2023-08-22 17:51 UTC, camertron commented
Looks like I don't have CI set up to run tests on PRs. Just ran the tests locally though and everything looks 👍

2023-08-22 17:51 UTC, merged